site_name: Smart Farming
site_url: https://keepsimpler.github.io/smartfarming/
sit_author: Wenfeng Feng

theme:
  name: material
  features:
    # - toc.integrate
    - navigation.indexes

# Page tree
nav:
  # - Content: index.md
  - Introduction: introduction.md
  - Disease identification:
    - disease/index.md
    - Explore PlantVillage: disease/explore-plantvillage.md


extra_css:
  - stylesheets/extra.css


markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format