site_name: Smart Farming
site_url: https://keepsimpler.github.io/smartfarming/
site_author: Wenfeng Feng

theme:
  name: material
  custom_dir: overrides
  features:
    - toc.integrate
    - navigation.tabs
  favicon: assets/favicon.png

# Page tree
nav:
  - Home: index.md
  - Introduction: introduction.md
  - Disease identification:
    - Introduction: disease/index.md
    - Disease classification on PlantVillage: disease/classification-on-plantvillage-2.ipynb
    - Disease detection on PlandDoc: disease/detection-on-plantdoc.ipynb

extra_css:
  - stylesheets/extra.css

plugins:
  - mknotebooks:
      execute: false
      # enable_default_jupyter_cell_styling: false
      # enable_default_pandas_dataframe_styling: false      

markdown_extensions:
  - def_list
  - tables
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format